/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedShareTargetRouteImport } from './routes/_authed/share-target'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedRemindersRouteImport } from './routes/_authed/reminders'
import { Route as AuthedAiUsageRouteImport } from './routes/_authed/ai-usage'
import { Route as AuthedImagesIdRouteImport } from './routes/_authed/images.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedShareTargetRoute = AuthedShareTargetRouteImport.update({
  id: '/share-target',
  path: '/share-target',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedRemindersRoute = AuthedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAiUsageRoute = AuthedAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedImagesIdRoute = AuthedImagesIdRouteImport.update({
  id: '/images/$id',
  path: '/images/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/ai-usage': typeof AuthedAiUsageRoute
  '/reminders': typeof AuthedRemindersRoute
  '/settings': typeof AuthedSettingsRoute
  '/share-target': typeof AuthedShareTargetRoute
  '/images/$id': typeof AuthedImagesIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ai-usage': typeof AuthedAiUsageRoute
  '/reminders': typeof AuthedRemindersRoute
  '/settings': typeof AuthedSettingsRoute
  '/share-target': typeof AuthedShareTargetRoute
  '/': typeof AuthedIndexRoute
  '/images/$id': typeof AuthedImagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/ai-usage': typeof AuthedAiUsageRoute
  '/_authed/reminders': typeof AuthedRemindersRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/share-target': typeof AuthedShareTargetRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/images/$id': typeof AuthedImagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-usage'
    | '/reminders'
    | '/settings'
    | '/share-target'
    | '/images/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ai-usage'
    | '/reminders'
    | '/settings'
    | '/share-target'
    | '/'
    | '/images/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/ai-usage'
    | '/_authed/reminders'
    | '/_authed/settings'
    | '/_authed/share-target'
    | '/_authed/'
    | '/_authed/images/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/share-target': {
      id: '/_authed/share-target'
      path: '/share-target'
      fullPath: '/share-target'
      preLoaderRoute: typeof AuthedShareTargetRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/reminders': {
      id: '/_authed/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthedRemindersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/ai-usage': {
      id: '/_authed/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AuthedAiUsageRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/images/$id': {
      id: '/_authed/images/$id'
      path: '/images/$id'
      fullPath: '/images/$id'
      preLoaderRoute: typeof AuthedImagesIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAiUsageRoute: typeof AuthedAiUsageRoute
  AuthedRemindersRoute: typeof AuthedRemindersRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedShareTargetRoute: typeof AuthedShareTargetRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedImagesIdRoute: typeof AuthedImagesIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAiUsageRoute: AuthedAiUsageRoute,
  AuthedRemindersRoute: AuthedRemindersRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedShareTargetRoute: AuthedShareTargetRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedImagesIdRoute: AuthedImagesIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
